let data = [
  { x: 0, y: 0, value: "" },
  { x: 0, y: 1, value: "" },
  { x: 0, y: 2, value: "" },
  { x: 0, y: 3, value: "" },
  { x: 0, y: 4, value: "" },
  { x: 0, y: 5, value: "" },
  { x: 0, y: 6, value: "" },
  { x: 1, y: 0, value: "" },
  { x: 1, y: 1, value: "" },
  { x: 1, y: 2, value: "" },
  { x: 1, y: 3, value: "" },
  { x: 1, y: 4, value: "" },
  { x: 1, y: 5, value: "" },
  { x: 1, y: 6, value: "" },
  { x: 2, y: 0, value: "" },
  { x: 2, y: 1, value: "" },
  { x: 2, y: 2, value: "" },
  { x: 2, y: 3, value: "" },
  { x: 2, y: 4, value: "" },
  { x: 2, y: 5, value: "" },
  { x: 2, y: 6, value: "" },
  { x: 3, y: 0, value: "" },
  { x: 3, y: 1, value: "" },
  { x: 3, y: 2, value: "" },
  { x: 3, y: 3, value: "" },
  { x: 3, y: 4, value: "" },
  { x: 3, y: 5, value: "" },
  { x: 3, y: 6, value: "" },
  { x: 4, y: 0, value: "" },
  { x: 4, y: 1, value: "" },
  { x: 4, y: 2, value: "" },
  { x: 4, y: 3, value: "" },
  { x: 4, y: 4, value: "" },
  { x: 4, y: 5, value: "" },
  { x: 4, y: 6, value: "" },
  { x: 5, y: 0, value: "" },
  { x: 5, y: 1, value: "" },
  { x: 5, y: 2, value: "" },
  { x: 5, y: 3, value: "" },
  { x: 5, y: 4, value: "" },
  { x: 5, y: 5, value: "" },
  { x: 5, y: 6, value: "" },
];

export default data;
